name: Documentation Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Markdown files
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown-link-check-config.json'
    
    - name: Validate document structure
      run: |
        echo "Checking required files..."
        required_files=(
          "README.md"
          "LICENSE"
          "CONTRIBUTING.md"
          "CHANGELOG.md"
          "1-启动指令库/快速启动指令.md"
          "2-标准工作指南/完整工作指南.md"
          "3-产品类型模板/交易系统模板.md"
          "4-文档模板库/主文档模板.md"
          "5-使用示例/使用说明.md"
          "6-工具支持/质量检查清单.md"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Missing required file: $file"
            exit 1
          else
            echo "✅ Found: $file"
          fi
        done
        
        echo "All required files are present!"
    
    - name: Check file encoding
      run: |
        echo "Checking file encoding..."
        find . -name "*.md" -exec file {} \; | grep -v "UTF-8" && exit 1 || echo "All files are UTF-8 encoded"
